### ISSUE TITLE
Beeflang's params keyword doesn't interop well

### ISSUE THREAD

**Issue by RogueMacro** [jazzbre/bgfx-beef#1]
I discovered that the method `dbg_text_printf` uses `params` instead of `...`. After changing it to triple dots it works just fine. Beforehand it seemed like non of the extra args were passed at all. I think that `...` is what is used for interop. I don't know if it's possible with `params`, but it doesn't work for me.

**Comment by jazzbre** [comment]
Already fixed, need to push a bgfx PR before it can end in here though. Thanks!

**Comment by RogueMacro** [comment]
@jazzbre  Also, do you think default parameters could be a thing? It would simplify my bgfx-learning process since I wouldn't have to look it up in the API reference :) Topic for another issue?

**Comment by jazzbre** [comment]
The problem is that bgfx bindings are generated via IDL and there's no default parameters in the C API which is used as source in the IDL generation.

**Comment by jazzbre** [comment]
bgfx updated to latest with the ellipsis PR. Thanks for reporting this!
